FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

ADD requirements.txt /tmp/

RUN apt update && apt install -y \
    build-essential \
    ffmpeg \
    libsm6 \
    libxext6 \
    git \
    vim \
    cmake \
    g++ \
    wget \
    libboost-all-dev \
    pkg-config \
    && conda install -c conda-forge pybind11


SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# quiet conda + no prompts
RUN conda config --system --set always_yes true \
 && conda config --system --set changeps1 false

# upgrade cmake (and ninja) in *base* so /opt/conda/bin/cmake is new enough
RUN conda install -n base -c conda-forge "cmake>=3.29" "ninja" \
 && cmake --version

RUN conda create -q -n pogema python=3.10 \
 && conda run -n pogema python -V \
 && conda run -n pogema pip install --no-cache-dir -r /tmp/requirements.txt \
 && conda run -n pogema pip install --no-cache-dir importlib-metadata==4.13.0 --force-reinstall \
 && conda clean -afy

RUN wget -q https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz \
    && tar -xzf eigen-3.3.9.tar.gz \
    && mkdir -p eigen-3.3.9/build \
    && cd eigen-3.3.9/build \
    && cmake .. \
    && make install \
    && cd ../.. \
    && rm -rf eigen-3.3.9 eigen-3.3.9.tar.gz

RUN wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-1.14.1.tgz \
    && tar -xf onnxruntime-linux-x64-1.14.1.tgz \
    && cp onnxruntime-linux-x64-1.14.1/lib/* /usr/lib/ && cp onnxruntime-linux-x64-1.14.1/include/* /usr/include/

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate pogema && exec \"$@\"", "--"]
